import { ReqItem } from './requisitions.model';

export const allItems: ReqItem[] =
  [{
    id: 1,
    title: 'Keylex',
    status: 'Yellow',
    dateCreated: '02/03/2018',
    candCount: 37,
    city: 'Macon',
    state: 'Georgia'
  }, {
    id: 2,
    title: 'Overhold',
    status: 'Puce',
    dateCreated: '04/06/2018',
    candCount: 89,
    city: 'Washington',
    state: 'District of Columbia'
  }, {
    id: 3,
    title: 'Stronghold',
    status: 'Maroon',
    dateCreated: '11/09/2019',
    candCount: 84,
    city: 'Oklahoma City',
    state: 'Oklahoma'
  }, {
    id: 4,
    title: 'Greenlam',
    status: 'Orange',
    dateCreated: '01/04/2020',
    candCount: 88,
    city: 'Huntington',
    state: 'West Virginia'
  }, {
    id: 5,
    title: 'Zaam-Dox',
    status: 'Khaki',
    dateCreated: '06/03/2018',
    candCount: 11,
    city: 'Inglewood',
    state: 'California'
  }, {
    id: 6,
    title: 'Fix San',
    status: 'Aquamarine',
    dateCreated: '08/29/2019',
    candCount: 61,
    city: 'Scottsdale',
    state: 'Arizona'
  }, {
    id: 7,
    title: 'Span',
    status: 'Orange',
    dateCreated: '08/21/2019',
    candCount: 25,
    city: 'Indianapolis',
    state: 'Indiana'
  }, {
    id: 8,
    title: 'Sub-Ex',
    status: 'Crimson',
    dateCreated: '08/05/2018',
    candCount: 57,
    city: 'El Paso',
    state: 'Texas'
  }, {
    id: 9,
    title: 'It',
    status: 'Turquoise',
    dateCreated: '12/27/2019',
    candCount: 73,
    city: 'Providence',
    state: 'Rhode Island'
  }, {
    id: 10,
    title: 'Biodex',
    status: 'Purple',
    dateCreated: '07/04/2018',
    candCount: 59,
    city: 'Dallas',
    state: 'Texas'
  }, {
    id: 11,
    title: 'Alphazap',
    status: 'Blue',
    dateCreated: '10/02/2019',
    candCount: 72,
    city: 'Washington',
    state: 'District of Columbia'
  }, {
    id: 12,
    title: 'Span',
    status: 'Orange',
    dateCreated: '11/10/2018',
    candCount: 25,
    city: 'Savannah',
    state: 'Georgia'
  }, {
    id: 13,
    title: 'Subin',
    status: 'Blue',
    dateCreated: '04/17/2019',
    candCount: 85,
    city: 'Miami',
    state: 'Florida'
  }, {
    id: 14,
    title: 'Alphazap',
    status: 'Red',
    dateCreated: '10/27/2019',
    candCount: 80,
    city: 'Houston',
    state: 'Texas'
  }, {
    id: 15,
    title: 'Zathin',
    status: 'Mauv',
    dateCreated: '01/16/2018',
    candCount: 30,
    city: 'Burbank',
    state: 'California'
  }, {
    id: 16,
    title: 'Quo Lux',
    status: 'Orange',
    dateCreated: '11/09/2019',
    candCount: 52,
    city: 'Bradenton',
    state: 'Florida'
  }, {
    id: 17,
    title: 'Fix San',
    status: 'Khaki',
    dateCreated: '01/23/2019',
    candCount: 99,
    city: 'Hartford',
    state: 'Connecticut'
  }, {
    id: 18,
    title: 'Job',
    status: 'Goldenrod',
    dateCreated: '12/19/2019',
    candCount: 10,
    city: 'Charlotte',
    state: 'North Carolina'
  }, {
    id: 19,
    title: 'Tresom',
    status: 'Turquoise',
    dateCreated: '03/30/2019',
    candCount: 39,
    city: 'Jacksonville',
    state: 'Florida'
  }, {
    id: 20,
    title: 'Asoka',
    status: 'Aquamarine',
    dateCreated: '04/04/2018',
    candCount: 6,
    city: 'Chicago',
    state: 'Illinois'
  }, {
    id: 21,
    title: 'Veribet',
    status: 'Green',
    dateCreated: '05/10/2018',
    candCount: 86,
    city: 'Muncie',
    state: 'Indiana'
  }, {
    id: 22,
    title: 'Zaam-Dox',
    status: 'Teal',
    dateCreated: '08/10/2018',
    candCount: 55,
    city: 'New York City',
    state: 'New York'
  }, {
    id: 23,
    title: 'Bitchip',
    status: 'Turquoise',
    dateCreated: '05/04/2018',
    candCount: 64,
    city: 'Tucson',
    state: 'Arizona'
  }, {
    id: 24,
    title: 'Aerified',
    status: 'Indigo',
    dateCreated: '05/06/2018',
    candCount: 95,
    city: 'South Lake Tahoe',
    state: 'California'
  }, {
    id: 25,
    title: 'Sonair',
    status: 'Crimson',
    dateCreated: '12/12/2018',
    candCount: 38,
    city: 'Milwaukee',
    state: 'Wisconsin'
  }, {
    id: 26,
    title: 'Y-Solowarm',
    status: 'Violet',
    dateCreated: '05/05/2019',
    candCount: 6,
    city: 'San Francisco',
    state: 'California'
  }, {
    id: 27,
    title: 'Stronghold',
    status: 'Crimson',
    dateCreated: '02/17/2019',
    candCount: 90,
    city: 'Glendale',
    state: 'Arizona'
  }, {
    id: 28,
    title: 'Domainer',
    status: 'Aquamarine',
    dateCreated: '08/21/2018',
    candCount: 5,
    city: 'Madison',
    state: 'Wisconsin'
  }, {
    id: 29,
    title: 'Sub-Ex',
    status: 'Puce',
    dateCreated: '11/15/2019',
    candCount: 26,
    city: 'Spartanburg',
    state: 'South Carolina'
  }, {
    id: 30,
    title: 'Domainer',
    status: 'Yellow',
    dateCreated: '10/18/2018',
    candCount: 22,
    city: 'Washington',
    state: 'District of Columbia'
  }, {
    id: 31,
    title: 'Flowdesk',
    status: 'Green',
    dateCreated: '09/28/2018',
    candCount: 45,
    city: 'Saint Paul',
    state: 'Minnesota'
  }, {
    id: 32,
    title: 'Daltfresh',
    status: 'Yellow',
    dateCreated: '12/02/2018',
    candCount: 76,
    city: 'Richmond',
    state: 'Virginia'
  }, {
    id: 33,
    title: 'Bitwolf',
    status: 'Teal',
    dateCreated: '06/13/2019',
    candCount: 36,
    city: 'Garland',
    state: 'Texas'
  }, {
    id: 34,
    title: 'Zaam-Dox',
    status: 'Orange',
    dateCreated: '06/21/2019',
    candCount: 44,
    city: 'Lima',
    state: 'Ohio'
  }, {
    id: 35,
    title: 'Domainer',
    status: 'Purple',
    dateCreated: '07/21/2018',
    candCount: 65,
    city: 'Irving',
    state: 'Texas'
  }, {
    id: 36,
    title: 'Andalax',
    status: 'Turquoise',
    dateCreated: '11/12/2018',
    candCount: 48,
    city: 'El Paso',
    state: 'Texas'
  }, {
    id: 37,
    title: 'Stringtough',
    status: 'Violet',
    dateCreated: '03/19/2019',
    candCount: 5,
    city: 'Fort Wayne',
    state: 'Indiana'
  }, {
    id: 38,
    title: 'Sonsing',
    status: 'Yellow',
    dateCreated: '07/09/2019',
    candCount: 70,
    city: 'New York City',
    state: 'New York'
  }, {
    id: 39,
    title: 'Zamit',
    status: 'Indigo',
    dateCreated: '05/26/2019',
    candCount: 72,
    city: 'Bakersfield',
    state: 'California'
  }, {
    id: 40,
    title: 'Vagram',
    status: 'Turquoise',
    dateCreated: '12/10/2019',
    candCount: 34,
    city: 'Jacksonville',
    state: 'Florida'
  }, {
    id: 41,
    title: 'Sonair',
    status: 'Turquoise',
    dateCreated: '05/26/2018',
    candCount: 84,
    city: 'Fargo',
    state: 'North Dakota'
  }, {
    id: 42,
    title: 'Toughjoyfax',
    status: 'Aquamarine',
    dateCreated: '08/03/2019',
    candCount: 67,
    city: 'Juneau',
    state: 'Alaska'
  }, {
    id: 43,
    title: 'Andalax',
    status: 'Pink',
    dateCreated: '03/04/2019',
    candCount: 68,
    city: 'Madison',
    state: 'Wisconsin'
  }, {
    id: 44,
    title: 'Aerified',
    status: 'Purple',
    dateCreated: '04/01/2019',
    candCount: 5,
    city: 'Dallas',
    state: 'Texas'
  }, {
    id: 45,
    title: 'Tampflex',
    status: 'Purple',
    dateCreated: '08/04/2018',
    candCount: 44,
    city: 'Mansfield',
    state: 'Ohio'
  }, {
    id: 46,
    title: 'Tampflex',
    status: 'Turquoise',
    dateCreated: '08/01/2019',
    candCount: 86,
    city: 'Irvine',
    state: 'California'
  }, {
    id: 47,
    title: 'Transcof',
    status: 'Khaki',
    dateCreated: '05/03/2018',
    candCount: 62,
    city: 'Atlanta',
    state: 'Georgia'
  }, {
    id: 48,
    title: 'Sonsing',
    status: 'Puce',
    dateCreated: '10/03/2019',
    candCount: 72,
    city: 'Roanoke',
    state: 'Virginia'
  }, {
    id: 49,
    title: 'Holdlamis',
    status: 'Puce',
    dateCreated: '01/08/2018',
    candCount: 25,
    city: 'Baltimore',
    state: 'Maryland'
  }, {
    id: 50,
    title: 'Biodex',
    status: 'Orange',
    dateCreated: '02/04/2019',
    candCount: 30,
    city: 'Salt Lake City',
    state: 'Utah'
  }, {
    id: 51,
    title: 'Tresom',
    status: 'Turquoise',
    dateCreated: '06/05/2018',
    candCount: 38,
    city: 'North Little Rock',
    state: 'Arkansas'
  }, {
    id: 52,
    title: 'Trippledex',
    status: 'Red',
    dateCreated: '02/20/2018',
    candCount: 96,
    city: 'Denver',
    state: 'Colorado'
  }, {
    id: 53,
    title: 'Otcom',
    status: 'Mauv',
    dateCreated: '11/13/2019',
    candCount: 21,
    city: 'Akron',
    state: 'Ohio'
  }, {
    id: 54,
    title: 'Keylex',
    status: 'Maroon',
    dateCreated: '02/22/2018',
    candCount: 73,
    city: 'Arlington',
    state: 'Texas'
  }, {
    id: 55,
    title: 'Quo Lux',
    status: 'Teal',
    dateCreated: '04/19/2018',
    candCount: 75,
    city: 'Indianapolis',
    state: 'Indiana'
  }, {
    id: 56,
    title: 'Kanlam',
    status: 'Purple',
    dateCreated: '10/07/2019',
    candCount: 47,
    city: 'Charleston',
    state: 'West Virginia'
  }, {
    id: 57,
    title: 'Tampflex',
    status: 'Blue',
    dateCreated: '11/18/2019',
    candCount: 75,
    city: 'Orlando',
    state: 'Florida'
  }, {
    id: 58,
    title: 'Prodder',
    status: 'Violet',
    dateCreated: '11/14/2019',
    candCount: 25,
    city: 'San Antonio',
    state: 'Texas'
  }, {
    id: 59,
    title: 'Bigtax',
    status: 'Mauv',
    dateCreated: '05/20/2019',
    candCount: 81,
    city: 'Phoenix',
    state: 'Arizona'
  }, {
    id: 60,
    title: 'Prodder',
    status: 'Khaki',
    dateCreated: '06/03/2019',
    candCount: 20,
    city: 'Carol Stream',
    state: 'Illinois'
  }, {
    id: 61,
    title: 'Sub-Ex',
    status: 'Purple',
    dateCreated: '09/13/2018',
    candCount: 25,
    city: 'San Diego',
    state: 'California'
  }, {
    id: 62,
    title: 'Greenlam',
    status: 'Aquamarine',
    dateCreated: '09/20/2018',
    candCount: 33,
    city: 'Fort Wayne',
    state: 'Indiana'
  }, {
    id: 63,
    title: 'Zaam-Dox',
    status: 'Fuscia',
    dateCreated: '10/02/2018',
    candCount: 42,
    city: 'Roanoke',
    state: 'Virginia'
  }, {
    id: 64,
    title: 'Flexidy',
    status: 'Violet',
    dateCreated: '04/24/2018',
    candCount: 96,
    city: 'Des Moines',
    state: 'Iowa'
  }, {
    id: 65,
    title: 'Stronghold',
    status: 'Goldenrod',
    dateCreated: '12/30/2018',
    candCount: 29,
    city: 'Oakland',
    state: 'California'
  }, {
    id: 66,
    title: 'Tresom',
    status: 'Indigo',
    dateCreated: '05/02/2019',
    candCount: 68,
    city: 'Chicago',
    state: 'Illinois'
  }, {
    id: 67,
    title: 'Bigtax',
    status: 'Indigo',
    dateCreated: '05/27/2018',
    candCount: 96,
    city: 'Corpus Christi',
    state: 'Texas'
  }, {
    id: 68,
    title: 'Job',
    status: 'Khaki',
    dateCreated: '08/02/2018',
    candCount: 33,
    city: 'York',
    state: 'Pennsylvania'
  }, {
    id: 69,
    title: 'Span',
    status: 'Purple',
    dateCreated: '08/14/2019',
    candCount: 62,
    city: 'Miami',
    state: 'Florida'
  }, {
    id: 70,
    title: 'Voyatouch',
    status: 'Turquoise',
    dateCreated: '05/25/2019',
    candCount: 80,
    city: 'Hartford',
    state: 'Connecticut'
  }, {
    id: 71,
    title: 'Solarbreeze',
    status: 'Puce',
    dateCreated: '11/05/2018',
    candCount: 9,
    city: 'New York City',
    state: 'New York'
  }, {
    id: 72,
    title: 'Wrapsafe',
    status: 'Red',
    dateCreated: '05/07/2018',
    candCount: 32,
    city: 'Fort Worth',
    state: 'Texas'
  }, {
    id: 73,
    title: 'Holdlamis',
    status: 'Turquoise',
    dateCreated: '08/30/2019',
    candCount: 6,
    city: 'Flushing',
    state: 'New York'
  }, {
    id: 74,
    title: 'Toughjoyfax',
    status: 'Fuscia',
    dateCreated: '09/05/2018',
    candCount: 17,
    city: 'Washington',
    state: 'District of Columbia'
  }, {
    id: 75,
    title: 'Stringtough',
    status: 'Puce',
    dateCreated: '05/18/2018',
    candCount: 56,
    city: 'Henderson',
    state: 'Nevada'
  }, {
    id: 76,
    title: 'Y-Solowarm',
    status: 'Violet',
    dateCreated: '03/27/2019',
    candCount: 48,
    city: 'Colorado Springs',
    state: 'Colorado'
  }, {
    id: 77,
    title: 'Matsoft',
    status: 'Goldenrod',
    dateCreated: '01/29/2018',
    candCount: 89,
    city: 'Philadelphia',
    state: 'Pennsylvania'
  }, {
    id: 78,
    title: 'Voltsillam',
    status: 'Puce',
    dateCreated: '11/17/2019',
    candCount: 43,
    city: 'Winter Haven',
    state: 'Florida'
  }, {
    id: 79,
    title: 'Cardguard',
    status: 'Fuscia',
    dateCreated: '04/24/2018',
    candCount: 32,
    city: 'Brooklyn',
    state: 'New York'
  }, {
    id: 80,
    title: 'Quo Lux',
    status: 'Aquamarine',
    dateCreated: '12/04/2018',
    candCount: 100,
    city: 'Lake Charles',
    state: 'Louisiana'
  }, {
    id: 81,
    title: 'Voyatouch',
    status: 'Aquamarine',
    dateCreated: '07/19/2018',
    candCount: 49,
    city: 'Lansing',
    state: 'Michigan'
  }, {
    id: 82,
    title: 'Stim',
    status: 'Fuscia',
    dateCreated: '07/27/2019',
    candCount: 21,
    city: 'Cincinnati',
    state: 'Ohio'
  }, {
    id: 83,
    title: 'Keylex',
    status: 'Violet',
    dateCreated: '02/23/2019',
    candCount: 93,
    city: 'Dallas',
    state: 'Texas'
  }, {
    id: 84,
    title: 'Tresom',
    status: 'Puce',
    dateCreated: '04/17/2019',
    candCount: 25,
    city: 'Omaha',
    state: 'Nebraska'
  }, {
    id: 85,
    title: 'Daltfresh',
    status: 'Green',
    dateCreated: '10/04/2019',
    candCount: 69,
    city: 'Fayetteville',
    state: 'North Carolina'
  }, {
    id: 86,
    title: 'Konklab',
    status: 'Aquamarine',
    dateCreated: '05/08/2018',
    candCount: 99,
    city: 'Champaign',
    state: 'Illinois'
  }, {
    id: 87,
    title: 'Transcof',
    status: 'Mauv',
    dateCreated: '04/20/2018',
    candCount: 74,
    city: 'Atlanta',
    state: 'Georgia'
  }, {
    id: 88,
    title: 'Domainer',
    status: 'Red',
    dateCreated: '07/04/2018',
    candCount: 56,
    city: 'Clearwater',
    state: 'Florida'
  }, {
    id: 89,
    title: 'Stronghold',
    status: 'Mauv',
    dateCreated: '07/28/2018',
    candCount: 65,
    city: 'Topeka',
    state: 'Kansas'
  }, {
    id: 90,
    title: 'Bigtax',
    status: 'Violet',
    dateCreated: '03/18/2018',
    candCount: 17,
    city: 'Waterloo',
    state: 'Iowa'
  }, {
    id: 91,
    title: 'Temp',
    status: 'Indigo',
    dateCreated: '08/16/2018',
    candCount: 43,
    city: 'Portland',
    state: 'Oregon'
  }, {
    id: 92,
    title: 'Rank',
    status: 'Violet',
    dateCreated: '12/26/2019',
    candCount: 62,
    city: 'Green Bay',
    state: 'Wisconsin'
  }, {
    id: 93,
    title: 'Stim',
    status: 'Turquoise',
    dateCreated: '05/07/2018',
    candCount: 65,
    city: 'Jamaica',
    state: 'New York'
  }, {
    id: 94,
    title: 'Alpha',
    status: 'Mauv',
    dateCreated: '11/07/2018',
    candCount: 66,
    city: 'Jacksonville',
    state: 'Florida'
  }, {
    id: 95,
    title: 'It',
    status: 'Orange',
    dateCreated: '10/20/2019',
    candCount: 36,
    city: 'Brooklyn',
    state: 'New York'
  }, {
    id: 96,
    title: 'Sonsing',
    status: 'Pink',
    dateCreated: '05/28/2018',
    candCount: 6,
    city: 'Richmond',
    state: 'Virginia'
  }, {
    id: 97,
    title: 'Bytecard',
    status: 'Teal',
    dateCreated: '09/15/2018',
    candCount: 91,
    city: 'Oakland',
    state: 'California'
  }, {
    id: 98,
    title: 'Aerified',
    status: 'Puce',
    dateCreated: '01/16/2019',
    candCount: 11,
    city: 'Denver',
    state: 'Colorado'
  }, {
    id: 99,
    title: 'Redhold',
    status: 'Crimson',
    dateCreated: '04/05/2018',
    candCount: 24,
    city: 'Lexington',
    state: 'Kentucky'
  }, {
    id: 100,
    title: 'Viva',
    status: 'Red',
    dateCreated: '03/07/2019',
    candCount: 36,
    city: 'Sacramento',
    state: 'California'
  }];
